name: microlearning
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  google_fonts: ^6.2.1
  logging: ^1.0.2
  dio: ^5.7.0
  logger: ^2.4.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  connectivity_plus: ^6.0.5
  get: ^4.6.1
  file_picker: ^8.1.4
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  http: ^1.2.2
  webview_flutter: ^4.10.0
  flutter_widget_from_html: ^0.15.3
  youtube_player_flutter: ^9.1.1
  universal_html: ^2.2.4
  flutter_pdfview: ^1.3.4
  open_filex: ^4.5.0
  permission_handler: ^11.3.1
  syncfusion_flutter_pdfviewer: ^28.1.33


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
